### ISSUE TITLE
add_or_replace_parameter() when URL doesn't end on slash

### ISSUE THREAD

**Issue by stummjr** [scrapy/w3lib#103]
Is this the expected behavior for `add_or_replace_parameter`?

```python
>>> from w3lib.url import add_or_replace_parameter
>>> add_or_replace_parameter('http://example.com', 'foo', 'bar')
'http://example.com?foo=bar'
```

Or should `add_or_replace_parameter` add a slash right after the netloc? Like: 

```http://example.com/?foo=bar```

Chrome seems to automatically add that slash, so I'm not sure if this should be handled by w3lib or by the http client.

**Comment by cathalgarvey** [comment]
Hi @stummjr - I think it's normal to have URLs that go straight to query without a path. And, IIRC some server/app frameworks are picky, and may even distinguish `foo.com/bar/` from `foo.com/bar`. In my opinion the present behaviour is correct.

**Comment by stummjr** [comment]
Yeah, it makes sense. Thanks @cathalgarvey! (feel free to close the issue, btw)
