### ISSUE TITLE
multiple parameters for add_or_replace_parameter

### ISSUE THREAD

**Issue by ejulio** [scrapy/w3lib#117]
Usually, when working with [`add_or_replace_parameter`](https://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.url.add_or_replace_parameter) we often end up writing something like
```
url = add_or_replace_parameter(url, 'q', 'query')
url = add_or_replace_parameter(url, 'location', 'US')
url = add_or_replace_parameter(url, 'count', 10)
```

What do you think of a similar function that works with a dictionary?

```
url = add_or_replace_parameters(url, {
  'q': 'query',
  'location': 'US',
  'count': 10
})
```

**Comment by dangra** [comment]
implemented in #121
