### ISSUE TITLE
remove_tags not working on html comments

### ISSUE THREAD

**Issue by mosynaq** [scrapy/w3lib#158]
I want to `remove_tags` from `'<div><!--<A href="/mypage.htm">-->text</div>'`. This is what I get as a result: `'-->text'`, while `'text'` is expected.

**Comment by Gallaecio** [comment]
I think there’s two parts here:

- I would expect you to get `<!--<A href="/mypage.htm">-->text`, and I think not getting that is a bug.

- You want `remove_tags` to support also removing comments, which I would say is a feature request.

**Comment by mosynaq** [comment]
I meant the latter. Since the HTML comment tag is an HTML tag too, it would be nice to remove them when removing HTML tags are asked. The former would be a good output if it is accessible through a parameter.

**Comment by Laerte** [comment]
@mosynaq If we call `remove_comments` before running the `remove_tags` the output will be the expected value.

```python
from w3lib.html import remove_tags, remove_comments

raw = '<div><!--<A href="/mypage.htm">-->text</div>'

assert remove_tags(remove_comments(raw)) == "text"
```

@Gallaecio If we consider HTML comments as tags we could just add a call to `remove_comments` on `remove_tags` function or we can add this additional parameter on `remove_tags` which one sound better?
