### ISSUE TITLE
should the canonize_url function convert an apostrophe to %27

### ISSUE THREAD

**Issue by bsekiewicz** [scrapy/w3lib#178]
I assume we want to normalize the url so that we don't have a problem with possible characters.

In this case, the lack of converting ' to %27 means that there may be problems saving the url in the SQL database.

**Comment by Gallaecio** [comment]
> I assume we want to normalize the url so that we don't have a problem with possible characters.

Actually, the point of that function is, I believe, to return the same string for 2 URLs that are equivalent. Storage into SQL is not a concern.

**Comment by bsekiewicz** [comment]
@Gallaecio 

I understand. In that case, are the two links below equivalent and correct?

www.example.com/sample's.xlsx
www.example.com/sample%27s.xlsx

Real case:
https://bipold.aotm.gov.pl/assets/files/zlecenia_mz/2018/140/RPT/140_OT.4320.13.2018_zespol_Tourette'a_2018.08.06.pdf
https://bipold.aotm.gov.pl/assets/files/zlecenia_mz/2018/140/RPT/140_OT.4320.13.2018_zespol_Tourette%27a_2018.08.06.pdf
