### ISSUE TITLE
Location of libw3.a

### ISSUE THREAD

**Issue by htan2013** [scrapy/w3lib#210]
Dear all,

I have compiled my w3lib 2.0.1 by using "python setup.py install" command.
I tried to install another app that requires the library path for w3, especially it was looking for a file for libw3.a:

![image](https://user-images.githubusercontent.com/77926698/217872724-f259fbf3-4760-41f3-a4dd-2adcc22fa5f8.png)

After the compilation of w3lib by "python setup.py install", I don't see any files named libw3.a in this directory. Do you know where I can find this file?

Thanks,
Haochen

**Comment by Gallaecio** [comment]
w3lib is not a compiled library, but an interpreted, pure-Python one. Please, talk to the provides of that “another app” and ask them about it, I am pretty sure w3lib is not the dependency you are supposed to install to build that other program.
