### ISSUE TITLE
remove_tags removes text inbetween < >

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/w3lib#31]
```python
>>> from w3lib.html import remove_tags
>>> TEXT = u'<span itemprop="name"> <Afgeschermd2> </span>'
>>> remove_tags(TEXT)
u'  '
>>> remove_tags(TEXT, keep=['Afgeschermd2'])
u' <Afgeschermd2> '
```

**Comment by dangra** [comment]
anything contained within '<>' is a tag even if not commonly seen. am I missing something?

**Comment by nramirezuy** [comment]
I think I messed up something while testing, because I'm not able to reproduce anymore against the site. BTW those '<' and '>' where actually '&lt;' and '&gt;'; or at least are now.
