### ISSUE TITLE
html.get_meta_refresh incorrectly parses url

### ISSUE THREAD

**Issue by Djayb6** [scrapy/w3lib#32]
I have an example of meta refresh tag which is correctly parsed by major browsers such as Chrome and Safari, but not by `html.get_meta_refresh`. Link: http://www.moveomed.de

    <meta http-equiv="refresh" content="0; URL=
    http://www.domain.de/index.php" />

Note the newline  between `URL=` and `http://`

This returns `(0.0, 'http://moveomed.de/%0Ahttp://moveomed.de/index.php')` whereas it should have returned `(0.0, 'http://moveomed.de/index.php')`

**Comment by Granitas** [comment]
text = '''<meta http-equiv="refresh" content="0; URL=\nhttp://www.moveomed.de" />'''
    print(get_meta_refresh(text))
    >>> (0.0, 'http://www.moveomed.de')

Seems to work fine or am I missing something?

**Comment by Djayb6** [comment]
@Granitas it has since been fixed with my pull request #33

**Comment by kmike** [comment]
Yeah, I think we should make a release with the fixes. //cc @dangra

**Comment by dangra** [comment]
v1.12.0 on the way.
