### ISSUE TITLE
It's not a good idead to parse HTML text using regular expressions

### ISSUE THREAD

**Issue by starrify** [scrapy/w3lib#70]
In [`w3lib.html`](https://github.com/scrapy/w3lib/blob/master/w3lib/html.py) regular expressions are used to parse HTML texts:

``` python
_ent_re = re.compile(r'&((?P<named>[a-z\d]+)|#(?P<dec>\d+)|#x(?P<hex>[a-f\d]+))(?P<semicolon>;?)', re.IGNORECASE)
_tag_re = re.compile(r'<[a-zA-Z\/!].*?>', re.DOTALL)
_baseurl_re = re.compile(six.u(r'<base\s[^>]*href\s*=\s*[\"\']\s*([^\"\'\s]+)\s*[\"\']'), re.I)
_meta_refresh_re = re.compile(six.u(r'<meta\s[^>]*http-equiv[^>]*refresh[^>]*content\s*=\s*(?P<quote>["\'])(?P<int>(\d*\.)?\d+)\s*;\s*url=\s*(?P<url>.*?)(?P=quote)'), re.DOTALL | re.IGNORECASE)
_cdata_re = re.compile(r'((?P<cdata_s><!\[CDATA\[)(?P<cdata_d>.*?)(?P<cdata_e>\]\]>))', re.DOTALL)
```

However this is definitely incorrect when it involves commented contents, e.g.

``` python
>>> from w3lib import html
>>> html.get_base_url("""<!-- <base href="http://example.com/" /> -->""")
'http://example.com/'
```

Introducing "heavier" utilities like `lxml` would solve this issue easily, but that might be an awful idea as `w3lib` aims to be lightweight & fast.  
Or maybe we could implement some quick parser merely for eliminating the commented parts.

Any ideas?

**Comment by kmike** [comment]
@starrify I believe the goal was indeed speed; also, these regexes may take e.g. only first 4096 bytes of the page, without the rest. Ideas about a proper solution are welcome! It should

a) be almost as fast as these regexes;
b) work on arbitrarily truncated HTML files.

**Comment by devspyrosv** [comment]
Just to add my 2 cents and to bump this issue, 
indeed, regex parsing of the html seems to miss commented out base tags and in some cases those commented out base tags point to different websites altogether.

**Comment by botzill** [comment]
Another issue here is that it does not ignore the commented tags. For example we may have a commented base tag like:

```
 <!--<base href="http://127.0.0.1" />-->
 <base href="http://www.example.com/" />

```

Of course according to `_baseurl_re` it will take the commented one. 

Any ideas on how can we solve this?

**Comment by devspyrosv** [comment]
What I ended up with was to remove html comments before using get_base_url.

**Comment by openandclose** [comment]
Hello, just for your reference.

I recently tested w3lib's prescan against 500 most popular websites.
I found three bugs (or different behaviors from html5 spec).

books.google.com:
`<meta http-equiv="content-type"content="text/html; charset=UTF-8">`
(no space between attributes)

mega.nz:
`<meta http-equiv="Content-Type" content="text/html, charset=UTF-8" />`
(comma, not semicolon)

stuff.co.nz:
`doc.write('<body onload=[...] <meta charset="utf-8"/>`
(matching '<body')

validator, jsdom and html5lib-python get encoding successfully.

...I don't know it is a good idea to fix these and make prescan regex even more complex.

**Comment by fonkwe** [comment]
Regular expressions are a tool that is insufficiently sophisticated to understand the constructs employed by HTML. HTML is not a regular language and hence cannot be parsed by regular expressions. HTML is a language of sufficient complexity that it cannot be parsed by regular expressions.
