### ISSUE TITLE
remove_tags_with_content not removing javascript content

### ISSUE THREAD

**Issue by steve-brandcrafter** [scrapy/w3lib#74]
I am using Python 3.5 & w3lib 1.14.2

Let's say we have the following HTML:

`    Before JS 
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-24343546-1']);
        _gaq.push(['_trackPageview']);
        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    After JS
`

And we use the following code to strip out the above section:

`full_text_no_script = remove_tags_with_content(full_text_dirty[0], ('script',))`

Assume full_text_dirty[0] contains the HTML above, the variable full_text_no_script will end up containing the following content:

`Before JS var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-24343546-1']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); After JS `

**Comment by redapple** [comment]
Hi @steve-brandcrafter , I'm not able to reproduce the issue, neither with 1.14.2 nor 1.15.
Here are my console logs in a Python 3.5 virtualenv:

```
(w3lib-1.14.2-py35) ~$ python -V
Python 3.5.2
(w3lib-1.14.2-py35) ~$ pip freeze
pkg-resources==0.0.0
six==1.10.0
w3lib==1.14.2
(w3lib-1.14.2-py35) paul@paul-SATELLITE-R830:~$ python
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> i = '''Before JS <script type="text/javascript"> var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-24343546-1']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); </script> After JS '''
>>> import w3lib.html
>>> w3lib.html.remove_tags_with_content(i, ('script',))
'Before JS  After JS '
>>> bi = b'''Before JS <script type="text/javascript"> var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-24343546-1']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); </script> After JS '''
>>> w3lib.html.remove_tags_with_content(bi, ('script',))
'Before JS  After JS '
```

**Comment by steve-brandcrafter** [comment]
Thanks for your reply.

I figured out what causes this issue.

Stripping line breaks using normalize-space breaks remove_tags_with_content.

This will cause the issue I described above:

```
full_text_dirty = response.xpath('normalize-space(/html/body)').extract()
full_text_no_script = remove_tags_with_content(full_text_dirty[0], ('script',))

```

Whereas this works correctly:

```
full_text_dirty = response.xpath('/html/body').extract()
full_text_no_script = remove_tags_with_content(full_text_dirty[0], ('script',))
```

Strange!

For reference, the URL I am scraping is www.kobodesign.com

**Comment by redapple** [comment]
[XPath's `normalize-space()`](https://www.w3.org/TR/xpath/#function-normalize-space) also removes the tags, as it strips whitespace from the string representation of the 1st node in the passed node-set.

And [XPath's `string()`](https://www.w3.org/TR/xpath/#function-string) itself concatenates [string-value](https://www.w3.org/TR/xpath/#dt-string-value) of descendant nodes.

The string value of a `<script>` element is the JavaScript snippet.

```
$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> t = '''<!DOCTYPE html>
... <html>
... <body>
... 
... <h1>JavaScript in Body</h1>
... 
... <p id="demo">A Paragraph.</p>
... 
... <button type="button" onclick="myFunction()">Try it</button>
... 
... <script>
... function myFunction() {
...     document.getElementById("demo").innerHTML = "Paragraph changed.";
... }
... </script>
... 
... </body>
... </html>
... 
... '''
>>> import scrapy
>>> selector = scrapy.Selector(text=t)
>>> selector.xpath('/html/body')
[<Selector xpath='/html/body' data='<body>\n\n<h1>JavaScript in Body</h1>\n\n<p '>]
>>> selector.xpath('/html/body').extract()
['<body>\n\n<h1>JavaScript in Body</h1>\n\n<p id="demo">A Paragraph.</p>\n\n<button type="button" onclick="myFunction()">Try it</button>\n\n<script>\nfunction myFunction() {\n    document.getElementById("demo").innerHTML = "Paragraph changed.";\n}\n</script>\n\n</body>']

>>> selector.xpath('string(//script)').extract()
['\nfunction myFunction() {\n    document.getElementById("demo").innerHTML = "Paragraph changed.";\n}\n']
>>> 

>>> selector.xpath('normalize-space(/html/body)').extract()
['JavaScript in Body A Paragraph. Try it function myFunction() { document.getElementById("demo").innerHTML = "Paragraph changed."; }']
>>> selector.xpath('normalize-space(/html/body)').extract_first()
'JavaScript in Body A Paragraph. Try it function myFunction() { document.getElementById("demo").innerHTML = "Paragraph changed."; }'
>>> 
```

You may want the try the trick we wrote about [in this blog post](https://blog.scrapinghub.com/2014/07/17/xpath-tips-from-the-web-scraping-trenches/), a variation on `//*[not(self::script or self::style)]/text()[normalize-space(.)]`:

```
>>> selector.xpath('/html/body/descendant-or-self::*[not(self::script or self::style)]/text()').extract()
['\n\n', 'JavaScript in Body', '\n\n', 'A Paragraph.', '\n\n', 'Try it', '\n\n', '\n\n']
>>> print("".join(selector.xpath('/html/body/descendant-or-self::*[not(self::script or self::style)]/text()').extract())
... )


JavaScript in Body

A Paragraph.

Try it




>>> print("".join(selector.xpath('/html/body/descendant-or-self::*[not(self::script or self::style)]/text()').extract()))


JavaScript in Body

A Paragraph.

Try it




>>> 
```

**Comment by steve-brandcrafter** [comment]
Thank you Paul. You are very helpful!
