### ISSUE TITLE
html encoded urls

### ISSUE THREAD

**Issue by jvanasco** [scrapy/w3lib#96]
the HTML5 spec (possibly 4) allows for urls to encode an ampersand character, which the browser will automatically decode.

To a browser, these two urls are identical:

    url1 = "http://example.com?foo=bar&bar=foo"
    url2 = "http://example.com?foo=bar&amp;bar=foo"

To `w3lib` (and `urlparse`) they are not:

    print w3lib.url.canonicalize_url(url1)
    # http://example.com/?bar=foo&foo=bar

    print w3lib.url.canonicalize_url(url2)
    # http://example.com/?amp=&bar=foo&foo=bar

**Comment by kmike** [comment]
Shouldn't this be handled at HTML parsing time? E.g. if the raw URL was 

`"http://example.com?foo=bar&amp;amp;bar=foo"`

then it'd be `http://example.com?foo=bar&amp;bar=foo` after unescaping, we shouldn't transform it further to `http://example.com?foo=bar&bar=foo`.

**Comment by redapple** [comment]
I second @kmike . I don't think it's w3lib's role to decode HTML entity references.
lxml for example correctly decode the `&`:
```
>>> import lxml.html
>>> t = '''<a href="http://example.com?foo=bar&amp;bar=foo">http://example.com?foo=bar&amp;bar=foo</a><br />'''
>>> doc = lxml.html.fromstring(t)
>>> doc.xpath('//@href')
['http://example.com?foo=bar&bar=foo']
```
@jvanasco , where did you have an issue with this?

**Comment by jvanasco** [comment]
The only place this has affected me is JSON data from a handful of end points and oembed services *that aren't declared to be html output*.  This is definitely more of a gotcha for dealing with lazy/malformed providers a which are plenty.  I was hoping urllib might pick it up lower level and correct (some web servers do that).

At the time I realized this, i was stressed out from the cleanup job and thought a warning or something about the need to ensure the input is parsed html may be a good idea here.

**Comment by Gallaecio** [comment]
I agree with @kmike and @redapple here. Even though it is a pain in the ass when this happens, it is not the responsibility of `canonicalize_url` to handle this.

It should not be fixed, because albeit weird `http://example.com/?foo=bar&amp;bar=foo` is a valid URL different from `http://example.com?foo=bar&bar=foo`, and so printing a warning may be wrong in itself.

@jvanasco Would you be OK with us closing this issue?

**Comment by jvanasco** [comment]
Yeah it’s fine with me. I run everything through a cleanup routine before it hits this function; I was just concerned for others. I do a lot of web indexing, and the percent of servers and pages that ignore RFCs is insanely higher than I thought it would be.

**Comment by Gallaecio** [comment]
Thank you!
